version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: payflow-db
    restart: always
    environment:
      POSTGRES_DB: payflow
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./payflow
    container_name: payflow-app
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payflow
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      JWT_SECRET: payflow-secret-key-muito-segura-2024-xyz
      JWT_EXPIRATION: 86400000
    depends_on:
      - postgres

volumes:
  postgres_data: