# Perfil de desenvolvimento
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/payflow
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=dev-secret-key-payflow-2024-nao-usar-em-prod
jwt.expiration=86400000

# Logs
logging.level.com.icaro.payflow=DEBUG
logging.pattern.console=%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n